# Generated by Django 3.2.4 on 2021-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('parent_id', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('pieces', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('is_parent', models.BooleanField(default=False)),
                ('boq_id', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='master_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
