# Generated by Django 3.2.4 on 2021-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_db',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
