# Generated by Django 3.2.4 on 2021-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_master_item_comp_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_item',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
