# Generated by Django 3.2.4 on 2021-06-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_master_item_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_item_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('comp_count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('components', models.TextField(blank=True, default=None, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
                ('boq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boq')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
