# Generated by Django 3.2.4 on 2021-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_master_item_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_item_edit',
            name='boq_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
