# Generated by Django 3.2.4 on 2021-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_master_item_edit_boq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_item_edit',
            name='master_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
