# Generated by Django 3.2.4 on 2021-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_master_item_edit_master_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='child_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('master_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('sell_price', models.FloatField(blank=True, default=0, null=True)),
                ('sell_amount', models.FloatField(blank=True, default=0, null=True)),
                ('remark', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('item_id',),
            },
        ),
        migrations.RenameField(
            model_name='item',
            old_name='code',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='boq',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='factor1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='factor2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='factor3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='factor4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dry_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='boq_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
