# Generated by Django 3.2.4 on 2021-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_child_master_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='factor1',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='factor2',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='factor3',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='factor4',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
