# Generated by Django 3.2.4 on 2021-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210626_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='remark',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
