# Generated by Django 3.2.4 on 2021-06-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_master_db_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
