# Generated by Django 3.2.4 on 2021-06-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
