# Generated by Django 3.2.4 on 2021-06-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_excel_boq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='excel_boq',
            new_name='excel_boq_data',
        ),
    ]
