# Generated by Django 3.2.4 on 2021-07-05 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_boq_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
