# Generated by Django 3.2.4 on 2021-07-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_boq_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_value', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('category_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
