# Generated by Django 3.2.4 on 2021-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='uom',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
