# Generated by Django 3.2.4 on 2021-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_master_db_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_master',
            name='quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
