# Generated by Django 3.2.4 on 2021-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_child_master_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
